In [1]:
import numpy as np

In [2]:
# P1
arr = np.eye(3) * 7

print(arr)

[[7. 0. 0.]
 [0. 7. 0.]
 [0. 0. 7.]]


In [3]:
# P2
arr = np.zeros((5, 5))

arr[0, :] = 1
arr[-1, :] = 1

arr[2, 2] = 5

print(arr)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [7]:
# P3
m = int(input("Enter m: "))
n = int(input("Enter n: "))

row = np.arange(1, n + 1)

arr = np.broadcast_to(row, (m, n))

print(arr)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
# P4
arr = np.arange(1, 21)

result = arr[(arr % 2 == 0) & (arr > 10)]

print(result)

[12 14 16 18 20]


In [6]:
# P5
arr = np.array([12, 7, 25, 18, 30, 10, 22, 15])

print("Sum:", np.sum(arr))
print("Average:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Index of maximum:", np.argmax(arr))

Sum: 139
Average: 17.375
Maximum: 30
Minimum: 7
Index of maximum: 4
